Document: timelapse
Title: Debian timelapse Manual
Author: <insert document author here>
Abstract: This manual describes what timelapse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/timelapse/timelapse.sgml.gz

Format: postscript
Files: /usr/share/doc/timelapse/timelapse.ps.gz

Format: text
Files: /usr/share/doc/timelapse/timelapse.text.gz

Format: HTML
Index: /usr/share/doc/timelapse/html/index.html
Files: /usr/share/doc/timelapse/html/*.html


